// Code generated by internal/generate/servicepackages/main.go; DO NOT EDIT.package kinesisanalyticsv2import (
	"context"	aws_sdkv1 "github.com/aws/aws-sdk-go/aws"
	session_sdkv1 "github.com/aws/aws-sdk-go/aws/session"
	kinesisanalyticsv2_sdkv1 "github.com/aws/aws-sdk-go/service/kinesisanalyticsv2"
	"github.com/hashicorp/terraform-provider-aws/internal/conns"
	"github.com/hashicorp/terraform-provider-aws/internal/types"
	"github.com/hashicorp/terraform-provider-aws/names"
)type servicePackage struct{} (p *servicePackage) FrameworkDataSources(ctx context.Context) []*types.ServicePackageFrameworkDataSource {
	return []*types.ServicePackageFrameworkDataSource{}
} (p *servicePackage) FrameworkResources(ctx context.Context) []*types.ServicePackageFrameworkResource {
	return []*types.ServicePackageFrameworkResource{}
} (p *servicePackage) SDKDataSources(ctx context.Context) []*types.ServicePackageSDKDataSource {
	return []*types.ServicePackageSDKDataSource{}
} (p *servicePackage) SDKResources(ctx context.Context) []*types.ServicePackageSDKResource {
	return []*types.ServicePackageSDKResource{
		{
			Factory:  ResourceApplication,
			TypeName: "aws_kinesisanalyticsv2_application",
			Name:     "Application",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "arn",
			},
		},
		{
			Factory:  ResourceApplicationSnapshot,
			TypeName: "aws_kinesisanalyticsv2_application_snapshot",
		},
	}
} (p *servicePackage) ServicePackageName() string {
	return names.KinesisAnalyticsV2
}// NewConn returns a new AWS SDK for Go v1 client for this service package's AWS API. (p *servicePackage) NewConn(ctx context.Context, config map[string]any) (*kinesisanalyticsv2_sdkv1.KinesisAnalyticsV2, error) {
	sess := config["session"].(*session_sdkv1.Session)	return kinesisanalyticsv2_sdkv1.New(sess.Copy(&aws_sdkv1.Config{Endpoint: aws_sdkv1.String(config["endpoint"].(string))})), nil
} ServicePackage(ctx context.Context) conns.ServicePackage {
	return &servicePackage{}
}
