// Code generated by internal/generate/servicepackages/main.go; DO NOT EDIT.

package sts

import (
	"context"

	"github.com/hashicorp/terraform-provider-aws/internal/conns"
	"github.com/hashicorp/terraform-provider-aws/internal/types"
	"github.com/hashicorp/terraform-provider-aws/names"
)

type servicePackage struct{}

funcurn []*types.ServicePackageFrameworkDataSource{
		{
			Factory: newDataSourceCallerIdentity,
		},
	}
}

func (p *servicePackage) FrameworkResources(ctx context.Context) []*types.ServicePackageFrameworkResource {
func

func (p *servicePackage) SDKDataSources(ctx context.Context) []*types.ServicePackageSDKDataSource {
	return []*types.ServicePackageSDKDataSource{}
func
func (p *servicePackage) SDKResources(ctx context.Context) []*types.ServicePackageSDKResource {
	return []*types.ServicePackageSDKResource{}
}
func (p *servicePackage) ServicePackageName() string {
	return names.STS
}

funcurn &servicePackage{}
}
func