// Code generated by internal/generate/tags/main.go; DO NOT EDIT.
package mediaconnectimport (
	"context"
	"fmt"	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/service/mediaconnect"
	"github.com/aws/aws-sdk-go/service/mediaconnect/mediaconnectiface"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-provider-aws/internal/conns"
	"github.com/hashicorp/terraform-provider-aws/internal/logging"
	tftags "github.com/hashicorp/terraform-provider-aws/internal/tags"
	"github.com/hashicorp/terraform-provider-aws/internal/types"
	"github.com/hashicorp/terraform-provider-aws/names"
)// listTags lists mediaconnect service tags.
// The identifier is typically the Amazon Resource Name (ARN), although
// it may also be a different identifier depending on the service.func listTags(ctx context.Context, conn mediaconnectiface.MediaConnectAPI, identifier string) (tftags.KeyValueTags, error) {
	input := &mediaconnect.ListTagsForResourceInput{
ResourceArn: aws.String(identifier),
	}	output, err := conn.ListTagsForResourceWithContext(ctx, input)	if err != nil {
turn tftags.New(ctx, nil), err
	}	return KeyValueTags(ctx, output.Tags), nil
}// ListTags lists mediaconnect service tags and set them in Context.
// It is called from outside this package.func (p *servicePackage) ListTags(ctx context.Context, meta any, identifier string) error {
	tags, err := listTags(ctx, meta.(*conns.AWSClient).MediaConnectConn(ctx), identifier)	if err != nil {
turn err
	}	if inContext, ok := tftags.FromContext(ctx); ok {
Context.TagsOut = types.Some(tags)
	}	return nil
}// map[string]*string handling// Tags returns mediaconnect service tags.func Tags(tags tftags.KeyValueTags) map[string]*string {
	return aws.StringMap(tags.Map())
}// KeyValueTags creates tftags.KeyValueTags from mediaconnect service tags.func KeyValueTags(ctx context.Context, tags map[string]*string) tftags.KeyValueTags {
	return tftags.New(ctx, tags)
}// getTagsIn returns mediaconnect service tags from Context.
// nil is returned if there are no input tags.func getTagsIn(ctx context.Context) map[string]*string {
	if inContext, ok := tftags.FromContext(ctx); ok {
 tags := Tags(inContext.TagsIn.UnwrapOrDefault()); len(tags) > 0 {
return tags	}	return nil
}// setTagsOut sets mediaconnect service tags in Context.func setTagsOut(ctx context.Context, tags map[string]*string) {
	if inContext, ok := tftags.FromContext(ctx); ok {
Context.TagsOut = types.Some(KeyValueTags(ctx, tags))
	}
}// updateTags updates mediaconnect service tags.
// The identifier is typically the Amazon Resource Name (ARN), although
// it may also be a different identifier depending on the service.func updateTags(ctx context.Context, conn mediaconnectiface.MediaConnectAPI, identifier string, oldTagsMap, newTagsMap any) error {
	oldTags := tftags.New(ctx, oldTagsMap)
	newTags := tftags.New(ctx, newTagsMap)	ctx = tflog.SetField(ctx, logging.KeyResourceId, identifier)	removedTags := oldTags.Removed(newTags)
	removedTags = removedTags.IgnoreSystem(names.MediaConnect)
	if len(removedTags) > 0 {
put := &mediaconnect.UntagResourceInput{
ResourceArn: aws.String(identifier),
TagKeys:tringSlice(removedTags.Keys()),
,rr := conn.UntagResourceWithContext(ctx, input)if e != nil {
return fmt.Errorf("untagging resource (%s): %w", identifier, err)	}	updatedTags := oldTags.Updated(newTags)
	updatedTags = updatedTags.IgnoreSystem(names.MediaConnect)
	if len(updatedTags) > 0 {
put := &mediaconnect.TagResourceInput{
ResourceArn: aws.String(identifier),
Tags:),
,rr := conn.TagResourceWithContext(ctx, input)if e != nil {
return fmt.Errorf("tagging resource (%s): %w", identifier, err)	}	return nil
}// UpdateTags updates mediaconnect service tags.
// It is called from outside this package.func (p *servicePackage) UpdateTags(ctx context.Context, meta any, identifier string, oldTags, newTags any) error {
	return updateTags(ctx, meta.(*conns.AWSClient).MediaConnectConn(ctx), identifier, oldTags, newTags)
}
