// Code generated by internal/generate/servicepackages/main.go; DO NOT EDIT.

package ce

import (
	"context"

	aws_sdkv1 "github.com/aws/aws-sdk-go/aws"
	session_sdkv1 "github.com/aws/aws-sdk-go/aws/session"
	costexplorer_sdkv1 "github.com/aws/aws-sdk-go/service/costexplorer"
	"github.com/hashicorp/terraform-provider-aws/internal/conns"
	"github.com/hashicorp/terraform-provider-aws/internal/types"
	"github.com/hashicorp/terraform-provider-aws/names"
)

type servicePackage struct{}
funcurn []*types.ServicePackageFrameworkDataSource{}
}
func (p *servicePackage) FrameworkResources(ctx context.Context) []*types.ServicePackageFrameworkResource {
func
func (p *servicePackage) SDKDataSources(ctx context.Context) []*types.ServicePackageSDKDataSource {
	return []*types.ServicePackageSDKDataSource{
funcactory:  DataSourceCostCategory,
			TypeName: "aws_ce_cost_category",
		},
		{
			Factory:  DataSourceTags,
			TypeName: "aws_ce_tags",
		},
	}
}
func (p *servicePackage) SDKResources(ctx context.Context) []*types.ServicePackageSDKResource {
	return []*types.ServicePackageSDKResource{
		{
funcypeName: "aws_ce_anomaly_monitor",
			Name:     "Anomaly Monitor",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "id",
			},
		},
		{
			Factory:  ResourceAnomalySubscription,
			TypeName: "aws_ce_anomaly_subscription",
			Name:     "Anomaly Subscription",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "id",
			},
		},
		{
			Factory:  ResourceCostAllocationTag,
			TypeName: "aws_ce_cost_allocation_tag",
		},
		{
			Factory:  ResourceCostCategory,
			TypeName: "aws_ce_cost_category",
			Name:     "Cost Category",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "id",
			},
		},
	}
}
func (p *servicePackage) ServicePackageName() string {
	return names.CE
}

funcs := config["session"].(*session_sdkv1.Session)

	return costexplorer_sdkv1.New(sess.Copy(&aws_sdkv1.Config{Endpoint: aws_sdkv1.String(config["endpoint"].(string))})), nil
}
func ServicePackage(ctx context.Context) conns.ServicePackage {funcurn &servicePackage{}
}
func