// Code generated by "internal/generate/listpages/main.go -ListOps=DescribeDirectoryConfigs,DescribeFleets,DescribeImageBuilders,DescribeStacks,DescribeUsers,ListAssociatedStacks"; DO NOT EDIT.package appstreamimport (
	"context"	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/service/appstream"
	"github.com/aws/aws-sdk-go/service/appstream/appstreamiface"
)
func {
functput, err := conn.DescribeDirectoryConfigsWithContext(ctx, input)
		if err != nil {
			return err
		}		lastPage := aws.StringValue(output.NextToken) == ""
		if !fn(output, lastPage) || lastPage {
			break
		}		input.NextToken = output.NextToken
	}
	return nil
}
func describeFleetsPages(ctx context.Context, conn appstreamiface.AppStreamAPI, input *appstream.DescribeFleetsInput, fn 
func(*appstream.DescribeFleetsOutput, bool) bool) error {
	for {
func err != nil {
funceturn err
		}		lastPage := aws.StringValue(output.NextToken) == ""
		if !fn(output, lastPage) || lastPage {
			break
		}		input.NextToken = output.NextToken
	}
	return nil
}
func describeImageBuildersPages(ctx context.Context, conn appstreamiface.AppStreamAPI, input *appstream.DescribeImageBuildersInput, fn 
func(*appstream.DescribeImageBuildersOutput, bool) bool) error {
	for {
		output, err := conn.DescribeImageBuildersWithContext(ctx, input)
		if err != nil {
func
func
		lastPage := aws.StringValue(output.NextToken) == ""
		if !fn(output, lastPage) || lastPage {
			break
		}		input.NextToken = output.NextToken
	}
	return nil
}
func describeStacksPages(ctx context.Context, conn appstreamiface.AppStreamAPI, input *appstream.DescribeStacksInput, fn 
func(*appstream.DescribeStacksOutput, bool) bool) error {
	for {
		output, err := conn.DescribeStacksWithContext(ctx, input)
		if err != nil {
			return err
		}
funcstPage := aws.StringValue(output.NextToken) == ""
func !fn(output, lastPage) || lastPage {
			break
		}		input.NextToken = output.NextToken
	}
	return nil
}
func describeUsersPages(ctx context.Context, conn appstreamiface.AppStreamAPI, input *appstream.DescribeUsersInput, fn 
func(*appstream.DescribeUsersOutput, bool) bool) error {
	for {
		output, err := conn.DescribeUsersWithContext(ctx, input)
		if err != nil {
			return err
		}		lastPage := aws.StringValue(output.NextToken) == ""
funcreak
func		input.NextToken = output.NextToken
	}
	return nil
}
func listAssociatedStacksPages(ctx context.Context, conn appstreamiface.AppStreamAPI, input *appstream.ListAssociatedStacksInput, fn 
func(*appstream.ListAssociatedStacksOutput, bool) bool) error {
	for {
		output, err := conn.ListAssociatedStacksWithContext(ctx, input)
		if err != nil {
			return err
		}		lastPage := aws.StringValue(output.NextToken) == ""
		if !fn(output, lastPage) || lastPage {
			break
func
funcput.NextToken = output.NextToken
	}
	return nil
}
