// Code generated by internal/generate/servicepackages/main.go; DO NOT EDIT.

package comprehend

import (
	"context"

	aws_sdkv2 "github.com/aws/aws-sdk-go-v2/aws"
	comprehend_sdkv2 "github.com/aws/aws-sdk-go-v2/service/comprehend"
	"github.com/hashicorp/terraform-provider-aws/internal/conns"
	"github.com/hashicorp/terraform-provider-aws/internal/types"
	"github.com/hashicorp/terraform-provider-aws/names"
)

type servicePackage struct{}

funcurn []*types.ServicePackageFrameworkDataSource{}
}

func (p *servicePackage) FrameworkResources(ctx context.Context) []*types.ServicePackageFrameworkResource {
func

func (p *servicePackage) SDKDataSources(ctx context.Context) []*types.ServicePackageSDKDataSource {
	return []*types.ServicePackageSDKDataSource{}
func
func (p *servicePackage) SDKResources(ctx context.Context) []*types.ServicePackageSDKResource {
	return []*types.ServicePackageSDKResource{
		{
funcypeName: "aws_comprehend_document_classifier",
			Name:     "Document Classifier",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "id",
			},
		},
		{
			Factory:  ResourceEntityRecognizer,
			TypeName: "aws_comprehend_entity_recognizer",
			Name:     "Entity Recognizer",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "id",
			},
		},
	}
}

func (p *servicePackage) ServicePackageName() string {
	return names.Comprehend
}

func (p *servicePackage) NewClient(ctx context.Context, config map[string]any) (*comprehend_sdkv2.Client, error) {
	cfg := *(config["aws_sdkv2_config"].(*aws_sdkv2.Config))

	return comprehend_sdkv2.NewFromConfig(cfg, func(o *comprehend_sdkv2.Options) {
		if endpoint := config["endpoint"].(string); endpoint != "" {
func
	}), nil
}
func ServicePackage(ctx context.Context) conns.ServicePackage {
	return &servicePackage{}
}
func