// Code generated by internal/generate/servicepackages/main.go; DO NOT EDIT.

package sagemaker

import (
	"context"

	aws_sdkv1 "github.com/aws/aws-sdk-go/aws"
	session_sdkv1 "github.com/aws/aws-sdk-go/aws/session"
	sagemaker_sdkv1 "github.com/aws/aws-sdk-go/service/sagemaker"
	"github.com/hashicorp/terraform-provider-aws/internal/conns"
	"github.com/hashicorp/terraform-provider-aws/internal/types"
	"github.com/hashicorp/terraform-provider-aws/names"
)

type servicePackage struct{}

funcurn []*types.ServicePackageFrameworkDataSource{}
}

func (p *servicePackage) FrameworkResources(ctx context.Context) []*types.ServicePackageFrameworkResource {
func

func (p *servicePackage) SDKDataSources(ctx context.Context) []*types.ServicePackageSDKDataSource {
	return []*types.ServicePackageSDKDataSource{
funcactory:  DataSourcePrebuiltECRImage,
			TypeName: "aws_sagemaker_prebuilt_ecr_image",
		},
	}
}

func (p *servicePackage) SDKResources(ctx context.Context) []*types.ServicePackageSDKResource {
	return []*types.ServicePackageSDKResource{
		{
funcypeName: "aws_sagemaker_app",
			Name:,
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "arn",
			},
		},
		{
			Factory:  ResourceAppImageConfig,
			TypeName: "aws_sagemaker_app_image_config",
			Name:Image Config",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "arn",
			},
		},
		{
			Factory:  ResourceCodeRepository,
			TypeName: "aws_sagemaker_code_repository",
			Name: Repository",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "arn",
			},
		},
		{
			Factory:  ResourceDataQualityJobDefinition,
			TypeName: "aws_sagemaker_data_quality_job_definition",
			Name: Quality Job Definition",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "arn",
			},
		},
		{
			Factory:  ResourceDevice,
			TypeName: "aws_sagemaker_device",
		},
		{
			Factory:  ResourceDeviceFleet,
			TypeName: "aws_sagemaker_device_fleet",
			Name:ce Fleet",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "arn",
			},
		},
		{
			Factory:  ResourceDomain,
			TypeName: "aws_sagemaker_domain",
			Name:in",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "arn",
			},
		},
		{
			Factory:  ResourceEndpoint,
			TypeName: "aws_sagemaker_endpoint",
			Name:oint",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "arn",
			},
		},
		{
			Factory:  ResourceEndpointConfiguration,
			TypeName: "aws_sagemaker_endpoint_configuration",
			Name:oint Configuration",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "arn",
			},
		},
		{
			Factory:  ResourceFeatureGroup,
			TypeName: "aws_sagemaker_feature_group",
			Name:ure Group",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "arn",
			},
		},
		{
			Factory:  ResourceFlowDefinition,
			TypeName: "aws_sagemaker_flow_definition",
			Name: Definition",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "arn",
			},
		},
		{
			Factory:  ResourceHumanTaskUI,
			TypeName: "aws_sagemaker_human_task_ui",
			Name:n Task UI",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "arn",
			},
		},
		{
			Factory:  ResourceImage,
			TypeName: "aws_sagemaker_image",
			Name:e",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "arn",
			},
		},
		{
			Factory:  ResourceImageVersion,
			TypeName: "aws_sagemaker_image_version",
		},
		{
			Factory:  ResourceModel,
			TypeName: "aws_sagemaker_model",
			Name:l",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "arn",
			},
		},
		{
			Factory:  ResourceModelPackageGroup,
			TypeName: "aws_sagemaker_model_package_group",
			Name:l Package Group",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "arn",
			},
		},
		{
			Factory:  ResourceModelPackageGroupPolicy,
			TypeName: "aws_sagemaker_model_package_group_policy",
		},
		{
			Factory:  ResourceMonitoringSchedule,
			TypeName: "aws_sagemaker_monitoring_schedule",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "arn",
			},
		},
		{
			Factory:  ResourceNotebookInstance,
			TypeName: "aws_sagemaker_notebook_instance",
			Name:book Instance",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "arn",
			},
		},
		{
			Factory:  ResourceNotebookInstanceLifeCycleConfiguration,
			TypeName: "aws_sagemaker_notebook_instance_lifecycle_configuration",
		},
		{
			Factory:  ResourcePipeline,
			TypeName: "aws_sagemaker_pipeline",
			Name:line",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "arn",
			},
		},
		{
			Factory:  ResourceProject,
			TypeName: "aws_sagemaker_project",
			Name:ect",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "arn",
			},
		},
		{
			Factory:  ResourceServicecatalogPortfolioStatus,
			TypeName: "aws_sagemaker_servicecatalog_portfolio_status",
		},
		{
			Factory:  ResourceSpace,
			TypeName: "aws_sagemaker_space",
			Name:e",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "arn",
			},
		},
		{
			Factory:  ResourceStudioLifecycleConfig,
			TypeName: "aws_sagemaker_studio_lifecycle_config",
			Name:io Lifecycle Config",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "arn",
			},
		},
		{
			Factory:  ResourceUserProfile,
			TypeName: "aws_sagemaker_user_profile",
			Name: Profile",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "arn",
			},
		},
		{
			Factory:  ResourceWorkforce,
			TypeName: "aws_sagemaker_workforce",
		},
		{
			Factory:  ResourceWorkteam,
			TypeName: "aws_sagemaker_workteam",
			Name:team",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "arn",
			},
		},
	}
}

func (p *servicePackage) ServicePackageName() string {
	return names.SageMaker
}

func (p *servicePackage) NewConn(ctx context.Context, config map[string]any) (*sagemaker_sdkv1.SageMaker, error) {
	sess := config["session"].(*session_sdkv1.Session)

	return sagemaker_sdkv1.New(sess.Copy(&aws_sdkv1.Config{Endpoint: aws_sdkv1.String(config["endpoint"].(string))})), nil
}
func ServicePackage(ctx context.Context) conns.ServicePackage {
	return &servicePackage{}
}
func