// Code generated by internal/generate/servicepackages/main.go; DO NOT EDIT.package resourceexplorer2import (
"context"aws_sdkv2 "github.com/aws/aws-sdk-go-v2/aws"
resourceexplorer2_sdkv2 "github.com/aws/aws-sdk-go-v2/service/resourceexplorer2"
"github.com/hashicorp/terraform-provider-aws/internal/conns"
"github.com/hashicorp/terraform-provider-aws/internal/types"
"github.com/hashicorp/terraform-provider-aws/names"
)type servicePackage struct{}
 (p *servicePackage) FrameworkDataSources(ctx context.Context) []*types.ServicePackageFrameworkDataSource {
return []*types.ServicePackageFrameworkDataSource{}
}
 (p *servicePackage) FrameworkResources(ctx context.Context) []*types.ServicePackageFrameworkResource {
return []*types.ServicePackageFrameworkResource{
{
Factory: newResourceIndex,
Name:"Index",
Tags: &types.ServicePackageResourceTags{
IdentifierAttribute: "id",
},
},
{
Factory: newResourceView,
Name:"View",
Tags: &types.ServicePackageResourceTags{
IdentifierAttribute: "id",
},
},
}
}
 (p *servicePackage) SDKDataSources(ctx context.Context) []*types.ServicePackageSDKDataSource {
return []*types.ServicePackageSDKDataSource{}
}
 (p *servicePackage) SDKResources(ctx context.Context) []*types.ServicePackageSDKResource {
return []*types.ServicePackageSDKResource{}
}
 (p *servicePackage) ServicePackageName() string {
return names.ResourceExplorer2
}// NewClient returns a new AWS SDK for Go v2 client for this service package's AWS API. (p *servicePackage) NewClient(ctx context.Context, config map[string]any) (*resourceexplorer2_sdkv2.Client, error) {
cfg := *(config["aws_sdkv2_config"].(*aws_sdkv2.Config))return resourceexplorer2_sdkv2.NewFromConfig(cfg,(o *resourceexplorer2_sdkv2.Options) {
if endpoint := config["endpoint"].(string); endpoint != "" {
o.BaseEndpoint = aws_sdkv2.String(endpoint)
}
}), nil
}
 ServicePackage(ctx context.Context) conns.ServicePackage {
return &servicePackage{}
}
