// Code generated by internal/generate/servicepackages/main.go; DO NOT EDIT.

package acm

import (
	"context"

	aws_sdkv2 "github.com/aws/aws-sdk-go-v2/aws"
	acm_sdkv2 "github.com/aws/aws-sdk-go-v2/service/acm"
	"github.com/hashicorp/terraform-provider-aws/internal/conns"
	"github.com/hashicorp/terraform-provider-aws/internal/types"
	"github.com/hashicorp/terraform-provider-aws/names"
)

type servicePackage struct{}

funcurn []*types.ServicePackageFrameworkDataSource{}
}

func (p *servicePackage) FrameworkResources(ctx context.Context) []*types.ServicePackageFrameworkResource {
func

func (p *servicePackage) SDKDataSources(ctx context.Context) []*types.ServicePackageSDKDataSource {
	return []*types.ServicePackageSDKDataSource{
funcactory:  dataSourceCertificate,
			TypeName: "aws_acm_certificate",
		},
	}
}

func (p *servicePackage) SDKResources(ctx context.Context) []*types.ServicePackageSDKResource {
	return []*types.ServicePackageSDKResource{
		{
funcypeName: "aws_acm_certificate",
			Name:ificate",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "id",
			},
		},
		{
			Factory:  resourceCertificateValidation,
			TypeName: "aws_acm_certificate_validation",
		},
	}
}

func (p *servicePackage) ServicePackageName() string {
	return names.ACM
}

func (p *servicePackage) NewClient(ctx context.Context, config map[string]any) (*acm_sdkv2.Client, error) {
	cfg := *(config["aws_sdkv2_config"].(*aws_sdkv2.Config))

	return acm_sdkv2.NewFromConfig(cfg, func(o *acm_sdkv2.Options) {
		if endpoint := config["endpoint"].(string); endpoint != "" {
func
	}), nil
}
func ServicePackage(ctx context.Context) conns.ServicePackage {
	return &servicePackage{}
}
func