// Code generated by internal/generate/servicepackages/main.go; DO NOT EDIT.

package dataexchange

import (
	"context"

	aws_sdkv1 "github.com/aws/aws-sdk-go/aws"
	session_sdkv1 "github.com/aws/aws-sdk-go/aws/session"
	dataexchange_sdkv1 "github.com/aws/aws-sdk-go/service/dataexchange"
	"github.com/hashicorp/terraform-provider-aws/internal/conns"
	"github.com/hashicorp/terraform-provider-aws/internal/types"
	"github.com/hashicorp/terraform-provider-aws/names"
)

type servicePackage struct{}


funcurn []*types.ServicePackageFrameworkDataSource{}
}


func (p *servicePackage) FrameworkResources(ctx context.Context) []*types.ServicePackageFrameworkResource {
func


func (p *servicePackage) SDKDataSources(ctx context.Context) []*types.ServicePackageSDKDataSource {
	return []*types.ServicePackageSDKDataSource{}
func

func (p *servicePackage) SDKResources(ctx context.Context) []*types.ServicePackageSDKResource {
	return []*types.ServicePackageSDKResource{
		{
funcypeName: "aws_dataexchange_data_set",
			Name: Set",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "arn",
			},
		},
		{
			Factory:  ResourceRevision,
			TypeName: "aws_dataexchange_revision",
			Name:Revision",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "arn",
			},
		},
	}
}


func (p *servicePackage) ServicePackageName() string {
	return names.DataExchange
}

func
func (p *servicePackage) NewConn(ctx context.Context, config map[string]any) (*dataexchange_sdkv1.DataExchange, error) {
	sess := config["session"].(*session_sdkv1.Session)

	return dataexchange_sdkv1.New(sess.Copy(&aws_sdkv1.Config{Endpoint: aws_sdkv1.String(config["endpoint"].(string))})), nil
}
func
func ServicePackage(ctx context.Context) conns.ServicePackage {
	return &servicePackage{}
}
func