// Code generated by internal/generate/servicepackages/main.go; DO NOT EDIT.

package athena

import (
	"context"

	aws_sdkv1 "github.com/aws/aws-sdk-go/aws"
	session_sdkv1 "github.com/aws/aws-sdk-go/aws/session"
	athena_sdkv1 "github.com/aws/aws-sdk-go/service/athena"
	"github.com/hashicorp/terraform-provider-aws/internal/conns"
	"github.com/hashicorp/terraform-provider-aws/internal/types"
	"github.com/hashicorp/terraform-provider-aws/names"
)

type servicePackage struct{}

funcurn []*types.ServicePackageFrameworkDataSource{}
}

func (p *servicePackage) FrameworkResources(ctx context.Context) []*types.ServicePackageFrameworkResource {
func

func (p *servicePackage) SDKDataSources(ctx context.Context) []*types.ServicePackageSDKDataSource {
	return []*types.ServicePackageSDKDataSource{}
func
func (p *servicePackage) SDKResources(ctx context.Context) []*types.ServicePackageSDKResource {
	return []*types.ServicePackageSDKResource{
		{
funcypeName: "aws_athena_data_catalog",
			Name: Catalog",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "arn",
			},
		},
		{
			Factory:  ResourceDatabase,
			TypeName: "aws_athena_database",
		},
		{
			Factory:  ResourceNamedQuery,
			TypeName: "aws_athena_named_query",
		},
		{
			Factory:  ResourceWorkGroup,
			TypeName: "aws_athena_workgroup",
			Name:Group",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "arn",
			},
		},
	}
}

func (p *servicePackage) ServicePackageName() string {
	return names.Athena
}

func (p *servicePackage) NewConn(ctx context.Context, config map[string]any) (*athena_sdkv1.Athena, error) {
	sess := config["session"].(*session_sdkv1.Session)

	return athena_sdkv1.New(sess.Copy(&aws_sdkv1.Config{Endpoint: aws_sdkv1.String(config["endpoint"].(string))})), nil
}
func ServicePackage(ctx context.Context) conns.ServicePackage {
	return &servicePackage{}
}
func