// Code generated by internal/generate/servicepackages/main.go; DO NOT EDIT.

package applicationinsights

import (
	"context"

	aws_sdkv1 "github.com/aws/aws-sdk-go/aws"
	session_sdkv1 "github.com/aws/aws-sdk-go/aws/session"
	applicationinsights_sdkv1 "github.com/aws/aws-sdk-go/service/applicationinsights"
	"github.com/hashicorp/terraform-provider-aws/internal/conns"
	"github.com/hashicorp/terraform-provider-aws/internal/types"
	"github.com/hashicorp/terraform-provider-aws/names"
)

type servicePackage struct{}funcurn []*types.ServicePackageFrameworkDataSource{}
}func (p *servicePackage) FrameworkResources(ctx context.Context) []*types.ServicePackageFrameworkResource {
	funcc (p *servicePackage) SDKDataSources(ctx context.Context) []*types.ServicePackageSDKDataSource {
	return []*types.ServicePackageSDKDataSource{}
}funcurn []*types.ServicePackageSDKResource{
		{
	funcypeName: "aws_applicationinsights_application",
			Name:     "Application",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: "arn",
			},
		},
	}
}func (p *servicePackage) ServicePackageName() string {
	return names.ApplicationInsights
}

/funcs := config["session"].(*session_sdkv1.Session)

	return applicationinsights_sdkv1.New(sess.Copy(&aws_sdkv1.Config{Endpoint: aws_sdkv1.String(config["endpoint"].(string))})), nil
}func ServicePackage(ctx context.Context) conns.ServicePackage {
	return &servicePackage{}
}
func