//Codegeneratedbyinternal/generate/tags/main.go;DONOTEDIT.
packagebatchimport(
"context"
"fmt""github.com/aws/aws-sdk-go/aws"
"github.com/aws/aws-sdk-go/service/batch"
"github.com/aws/aws-sdk-go/service/batch/batchiface"
"github.com/hashicorp/terraform-plugin-log/tflog"
"github.com/hashicorp/terraform-provider-aws/internal/conns"
"github.com/hashicorp/terraform-provider-aws/internal/logging"
tftags"github.com/hashicorp/terraform-provider-aws/internal/tags"
"github.com/hashicorp/terraform-provider-aws/internal/types"
"github.com/hashicorp/terraform-provider-aws/names"
)//listTagslistsbatchservicetags.
//TheidentifieristypicallytheAmazonResourceName(ARN),although
//itmayalsobeadifferentidentifierdependingontheservice.
funclistTags(ctxcontext.Context,connbatchiface.BatchAPI,identifierstring)(tftags.KeyValueTags,error){
input:=&batch.ListTagsForResourceInput{
ResourceArn:aws.String(identifier),
}output,err:=conn.ListTagsForResourceWithContext(ctx,input)iferr!=nil{
returntftags.New(ctx,nil),err
}returnKeyValueTags(ctx,output.Tags),nil
}//ListTagslistsbatchservicetagsandsettheminContext.
//Itiscalledfromoutsidethispackage.
func(p*servicePackage)ListTags(ctxcontext.Context,metaany,identifierstring)error{
tags,err:=listTags(ctx,meta.(*conns.AWSClient).BatchConn(ctx),identifier)iferr!=nil{
returnerr
}ifinContext,ok:=tftags.FromContext(ctx);ok{
inContext.TagsOut=types.Some(tags)
}returnnil
}//map[string]*stringhandling//Tagsreturnsbatchservicetags.
funcTags(tagstftags.KeyValueTags)map[string]*string{
returnaws.StringMap(tags.Map())
}//KeyValueTagscreatestftags.KeyValueTagsfrombatchservicetags.
funcKeyValueTags(ctxcontext.Context,tagsmap[string]*string)tftags.KeyValueTags{
returntftags.New(ctx,tags)
}//getTagsInreturnsbatchservicetagsfromContext.
//nilisreturnediftherearenoinputtags.
funcgetTagsIn(ctxcontext.Context)map[string]*string{
ifinContext,ok:=tftags.FromContext(ctx);ok{
iftags:=Tags(inContext.TagsIn.UnwrapOrDefault());len(tags)>0{
returntags
}
}returnnil
}//setTagsOutsetsbatchservicetagsinContext.
funcsetTagsOut(ctxcontext.Context,tagsmap[string]*string){
ifinContext,ok:=tftags.FromContext(ctx);ok{
inContext.TagsOut=types.Some(KeyValueTags(ctx,tags))
}
}//updateTagsupdatesbatchservicetags.
//TheidentifieristypicallytheAmazonResourceName(ARN),although
//itmayalsobeadifferentidentifierdependingontheservice.
funcupdateTags(ctxcontext.Context,connbatchiface.BatchAPI,identifierstring,oldTagsMap,newTagsMapany)error{
oldTags:=tftags.New(ctx,oldTagsMap)
newTags:=tftags.New(ctx,newTagsMap)ctx=tflog.SetField(ctx,logging.KeyResourceId,identifier)removedTags:=oldTags.Removed(newTags)
removedTags=removedTags.IgnoreSystem(names.Batch)
iflen(removedTags)>0{
input:=&batch.UntagResourceInput{
ResourceArn:aws.String(identifier),
TagKeys:aws.StringSlice(removedTags.Keys()),
}_,err:=conn.UntagResourceWithContext(ctx,input)iferr!=nil{
returnfmt.Errorf("untaggingresource(%s):%w",identifier,err)
}
}updatedTags:=oldTags.Updated(newTags)
updatedTags=updatedTags.IgnoreSystem(names.Batch)
iflen(updatedTags)>0{
input:=&batch.TagResourceInput{
ResourceArn:aws.String(identifier),
Tags:Tags(updatedTags),
}_,err:=conn.TagResourceWithContext(ctx,input)iferr!=nil{
returnfmt.Errorf("taggingresource(%s):%w",identifier,err)
}
}returnnil
}//UpdateTagsupdatesbatchservicetags.
//Itiscalledfromoutsidethispackage.
func(p*servicePackage)UpdateTags(ctxcontext.Context,metaany,identifierstring,oldTags,newTagsany)error{
returnupdateTags(ctx,meta.(*conns.AWSClient).BatchConn(ctx),identifier,oldTags,newTags)
}
