//Copyright(c)HashiCorp,Inc.
//SPDX-License-Identifier:MPL-2.0packageelasticacheimport(
"context"
"fmt"
"log"
"strings"
"time""github.com/YakDriver/regexache"
"github.com/aws/aws-sdk-go/aws"
"github.com/aws/aws-sdk-go/service/elasticache"
"github.com/hashicorp/aws-sdk-go-base/v2/awsv1shim/v2/tfawserr"
"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
"github.com/hashicorp/terraform-plugin-sdk/v2/helper/customdiff"
"github.com/hashicorp/terraform-plugin-sdk/v2/helper/retry"
"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"
"github.com/hashicorp/terraform-provider-aws/internal/conns"
"github.com/hashicorp/terraform-provider-aws/internal/errs"
"github.com/hashicorp/terraform-provider-aws/internal/errs/sdkdiag"
"github.com/hashicorp/terraform-provider-aws/internal/flex"
tftags"github.com/hashicorp/terraform-provider-aws/internal/tags"
"github.com/hashicorp/terraform-provider-aws/internal/tfresource"
"github.com/hashicorp/terraform-provider-aws/internal/types/nullable"
"github.com/hashicorp/terraform-provider-aws/internal/verify"
"github.com/hashicorp/terraform-provider-aws/names"
)//@SDKResource("aws_elasticache_replication_group",name="ReplicationGroup")
//@Tags(identifierAttribute="arn")funcResourceReplicationGroup()*schema.Resource{
//lintignore:R011
return&schema.Resource{
CreateWithoutTimeout:resourceReplicationGroupCreate,
ReadWithoutTimeout:resourceReplicationGroupRead,
UpdateWithoutTimeout:resourceReplicationGroupUpdate,
DeleteWithoutTimeout:resourceReplicationGroupDelete,Importer:&schema.ResourceImporter{
StateContext:schema.ImportStatePassthroughContext,
},Schema:map[string]*schema.Schema{
"apply_immediately":{
Type:schema.TypeBool,
Optional:true,
Computed:true,
},
"arn":{
Type:schema.TypeString,
Computed:true,
},
"at_rest_encryption_enabled":{
Type:schema.TypeBool,
Optional:true,
ForceNew:true,
Computed:true,
},
"auth_token":{
Type:schema.TypeString,
Optional:true,
Sensitive:true,
ValidateFunc:validReplicationGroupAuthToken,
ConflictsWith:[]string{"user_group_ids"},
},
"auto_minor_version_upgrade":{
Type:nullable.TypeNullableBool,
Optional:true,
Computed:true,
ValidateFunc:nullable.ValidateTypeStringNullableBool,
},
"automatic_failover_enabled":{
Type:schema.TypeBool,
Optional:true,
Default:false,
},
"cluster_enabled":{
Type:schema.TypeBool,
Computed:true,
},
"configuration_endpoint_address":{
Type:schema.TypeString,
Computed:true,
},
"data_tiering_enabled":{
Type:schema.TypeBool,
Optional:true,
Computed:true,
ForceNew:true,
},
"description":{
Type:schema.TypeString,
Optional:true,
Computed:true,
ValidateFunc:validation.StringIsNotEmpty,
},
"engine":{
Type:schema.TypeString,
Optional:true,
ForceNew:true,
Default:engineRedis,
ValidateFunc:validation.StringInSlice([]string{engineRedis},true),
},
"engine_version":{
Type:schema.TypeString,
Optional:true,
Computed:true,
ValidateFunc:validRedisVersionString,
},
"engine_version_actual":{
Type:schema.TypeString,
Computed:true,
},
"global_replication_group_id":{
Type:schema.TypeString,
Optional:true,
ForceNew:true,
Computed:true,
ConflictsWith:[]string{
"num_node_groups",
"parameter_group_name",
"engine",
"engine_version",
"node_type",
"security_group_names",
"transit_encryption_enabled",
"at_rest_encryption_enabled",
"snapshot_arns",
"snapshot_name",
},
},
"log_delivery_configuration":{
Type:schema.TypeSet,
Optional:true,
MaxItems:2,
Elem:&schema.Resource{
Schema:map[string]*schema.Schema{
"destination_type":{
Type:schema.TypeString,
Required:true,
ValidateFunc:validation.StringInSlice(elasticache.DestinationType_Values(),false),
},
"destination":{
Type:schema.TypeString,
Required:true,
},
"log_format":{
Type:schema.TypeString,
Required:true,
ValidateFunc:validation.StringInSlice(elasticache.LogFormat_Values(),false),
},
"log_type":{
Type:schema.TypeString,
Required:true,
ValidateFunc:validation.StringInSlice(elasticache.LogType_Values(),false),
},
},
},
},
"maintenance_window":{
Type:schema.TypeString,
Optional:true,
Computed:true,
StateFunc:
func(valinterface{})string{
//ElastiCachealwayschangesthemaintenancetolowercase
returnstrings.ToLower(val.(string))
},
ValidateFunc:verify.ValidOnceAWeekWindowFormat,
},
"member_clusters":{
Type:schema.TypeSet,
Computed:true,
Elem:&schema.Schema{Type:schema.TypeString},
Set:schema.HashString,
},
"multi_az_enabled":{
Type:schema.TypeBool,
Optional:true,
Default:false,
},
"node_type":{
Type:schema.TypeString,
Optional:true,
Computed:true,
},
"notification_topic_arn":{
Type:schema.TypeString,
Optional:true,
ValidateFunc:verify.ValidARN,
},
"num_cache_clusters":{
Type:schema.TypeInt,
Computed:true,
Optional:true,
ConflictsWith:[]string{"num_node_groups"},
},
"num_node_groups":{
Type:schema.TypeInt,
Optional:true,
Computed:true,
ConflictsWith:[]string{"num_cache_clusters","global_replication_group_id"},
},
"parameter_group_name":{
Type:schema.TypeString,
Optional:true,
Computed:true,
DiffSuppressFunc:
func(k,old,newstring,d*schema.ResourceData)bool{
returnstrings.HasPrefix(old,"global-datastore-")
},
},
"port":{
Type:schema.TypeInt,
Optional:true,
ForceNew:true,
DiffSuppressFunc:
func(k,old,newstring,d*schema.ResourceData)bool{
//SuppressdefaultRedisportswhennotdefined
if!d.IsNewResource()&&new=="0"&&old==defaultRedisPort{
returntrue
}
returnfalse
},
},
"preferred_cache_cluster_azs":{
Type:schema.TypeList,
Optional:true,
Elem:&schema.Schema{Type:schema.TypeString},
},
"primary_endpoint_address":{
Type:schema.TypeString,
Computed:true,
},
"reader_endpoint_address":{
Type:schema.TypeString,
Computed:true,
},
"replicas_per_node_group":{
Type:schema.TypeInt,
Optional:true,
Computed:true,
},
"replication_group_id":{
Type:schema.TypeString,
Required:true,
ForceNew:true,
ValidateFunc:validateReplicationGroupID,
StateFunc:
func(valinterface{})string{
returnstrings.ToLower(val.(string))
},
},
"security_group_names":{
Type:schema.TypeSet,
Optional:true,
Computed:true,
ForceNew:true,
Elem:&schema.Schema{Type:schema.TypeString},
Set:schema.HashString,
},
"security_group_ids":{
Type:schema.TypeSet,
Optional:true,
Computed:true,
Elem:&schema.Schema{Type:schema.TypeString},
Set:schema.HashString,
},
"snapshot_arns":{
Type:schema.TypeSet,
Optional:true,
ForceNew:true,
//Note:Unlikeaws_elasticache_cluster,thisdoesnothavealimitof1item.
Elem:&schema.Schema{
Type:schema.TypeString,
ValidateFunc:validation.All(
verify.ValidARN,
validation.StringDoesNotContainAny(","),
),
},
Set:schema.HashString,
},
"snapshot_retention_limit":{
Type:schema.TypeInt,
Optional:true,
ValidateFunc:validation.IntAtMost(35),
},
"snapshot_window":{
Type:schema.TypeString,
Optional:true,
Computed:true,
ValidateFunc:verify.ValidOnceADayWindowFormat,
},
"snapshot_name":{
Type:schema.TypeString,
Optional:true,
ForceNew:true,
},
"subnet_group_name":{
Type:schema.TypeString,
Optional:true,
Computed:true,
ForceNew:true,
},
names.AttrTags:tftags.TagsSchema(),
names.AttrTagsAll:tftags.TagsSchemaComputed(),
"transit_encryption_enabled":{
Type:schema.TypeBool,
Optional:true,
ForceNew:true,
Computed:true,
},
"user_group_ids":{
Type:schema.TypeSet,
Optional:true,
Elem:&schema.Schema{Type:schema.TypeString},
Set:schema.HashString,
ConflictsWith:[]string{"auth_token"},
},
"kms_key_id":{
Type:schema.TypeString,
ForceNew:true,
Optional:true,
},
"final_snapshot_identifier":{
Type:schema.TypeString,
Optional:true,
},
},SchemaVersion:1,
//SchemaVersion:1didnotincludeanystatechangesviaMigrateState.
//Performano-operationstateupgradeforTerraform0.12compatibility.
//FuturestatemigrationsshouldbeperformedwithStateUpgraders.
MigrateState:
func(vint,inst*terraform.InstanceState,metainterface{})(*terraform.InstanceState,error){
returninst,nil
},Timeouts:&schema.ResourceTimeout{
Create:schema.DefaultTimeout(ReplicationGroupDefaultCreatedTimeout),
Delete:schema.DefaultTimeout(ReplicationGroupDefaultDeletedTimeout),
Update:schema.DefaultTimeout(ReplicationGroupDefaultUpdatedTimeout),
},CustomizeDiff:customdiff.Sequence(
CustomizeDiffValidateReplicationGroupAutomaticFailover,
customizeDiffEngineVersionForceNewOnDowngrade,
customdiff.ComputedIf("member_clusters",
func(ctxcontext.Context,diff*schema.ResourceDiff,metainterface{})bool{
returndiff.HasChange("num_cache_clusters")||
diff.HasChange("num_node_groups")||
diff.HasChange("replicas_per_node_group")
}),
verify.SetTagsDiff,
),
}
}
funcresourceReplicationGroupCreate(ctxcontext.Context,d*schema.ResourceData,metainterface{})diag.Diagnostics{
vardiagsdiag.Diagnostics
conn:=meta.(*conns.AWSClient).ElastiCacheConn(ctx)replicationGroupID:=d.Get("replication_group_id").(string)
input:=&elasticache.CreateReplicationGroupInput{
ReplicationGroupId:aws.String(replicationGroupID),
Tags:getTagsIn(ctx),
}ifv,ok:=d.GetOk("description");ok{
input.ReplicationGroupDescription=aws.String(v.(string))
}ifv,ok:=d.GetOk("data_tiering_enabled");ok{
input.DataTieringEnabled=aws.Bool(v.(bool))
}ifv,ok:=d.GetOk("global_replication_group_id");ok{
input.GlobalReplicationGroupId=aws.String(v.(string))
}else{
//Thiscannotbehandledatplan-time
nodeType:=d.Get("node_type").(string)
ifnodeType==""{
returnsdkdiag.AppendErrorf(diags,`"node_type"isrequiredunless"global_replication_group_id"isset.`)
}
input.AutomaticFailoverEnabled=aws.Bool(d.Get("automatic_failover_enabled").(bool))
input.CacheNodeType=aws.String(nodeType)
input.Engine=aws.String(d.Get("engine").(string))
}ifv,ok:=d.GetOk("engine_version");ok{
input.EngineVersion=aws.String(v.(string))
}ifv,ok:=d.GetOk("auto_minor_version_upgrade");ok{
ifv,null,_:=nullable.Bool(v.(string)).Value();!null{
input.AutoMinorVersionUpgrade=aws.Bool(v)
}
}ifpreferredAZs,ok:=d.GetOk("preferred_cache_cluster_azs");ok{
input.PreferredCacheClusterAZs=flex.ExpandStringList(preferredAZs.([]interface{}))
}ifv,ok:=d.GetOk("parameter_group_name");ok{
input.CacheParameterGroupName=aws.String(v.(string))
}ifv,ok:=d.GetOk("port");ok{
input.Port=aws.Int64(int64(v.(int)))
}ifv,ok:=d.GetOk("subnet_group_name");ok{
input.CacheSubnetGroupName=aws.String(v.(string))
}ifSGNames:=d.Get("security_group_names").(*schema.Set);SGNames.Len()>0{
input.CacheSecurityGroupNames=flex.ExpandStringSet(SGNames)
}ifSGIds:=d.Get("security_group_ids").(*schema.Set);SGIds.Len()>0{
input.SecurityGroupIds=flex.ExpandStringSet(SGIds)
}ifsnaps:=d.Get("snapshot_arns").(*schema.Set);snaps.Len()>0{
input.SnapshotArns=flex.ExpandStringSet(snaps)
}ifv,ok:=d.GetOk("log_delivery_configuration");ok{
input.LogDeliveryConfigurations=[]*elasticache.LogDeliveryConfigurationRequest{}
v:=v.(*schema.Set).List()
for_,v:=rangev{
logDeliveryConfigurationRequest:=expandLogDeliveryConfigurations(v.(map[string]interface{}))
input.LogDeliveryConfigurations=append(input.LogDeliveryConfigurations,&logDeliveryConfigurationRequest)
}
}ifv,ok:=d.GetOk("maintenance_window");ok{
input.PreferredMaintenanceWindow=aws.String(v.(string))
}if_,ok:=d.GetOk("multi_az_enabled");ok{
input.MultiAZEnabled=aws.Bool(d.Get("multi_az_enabled").(bool))
}ifv,ok:=d.GetOk("notification_topic_arn");ok{
input.NotificationTopicArn=aws.String(v.(string))
}ifv,ok:=d.GetOk("kms_key_id");ok{
input.KmsKeyId=aws.String(v.(string))
}ifv,ok:=d.GetOk("snapshot_retention_limit");ok{
input.SnapshotRetentionLimit=aws.Int64(int64(v.(int)))
}ifv,ok:=d.GetOk("snapshot_window");ok{
input.SnapshotWindow=aws.String(v.(string))
}ifv,ok:=d.GetOk("snapshot_name");ok{
input.SnapshotName=aws.String(v.(string))
}if_,ok:=d.GetOk("transit_encryption_enabled");ok{
input.TransitEncryptionEnabled=aws.Bool(d.Get("transit_encryption_enabled").(bool))
}if_,ok:=d.GetOk("at_rest_encryption_enabled");ok{
input.AtRestEncryptionEnabled=aws.Bool(d.Get("at_rest_encryption_enabled").(bool))
}ifv,ok:=d.GetOk("auth_token");ok{
input.AuthToken=aws.String(v.(string))
}ifv,ok:=d.GetOk("num_node_groups");ok&&v!=0{
input.NumNodeGroups=aws.Int64(int64(v.(int)))
}ifv,ok:=d.GetOk("replicas_per_node_group");ok{
input.ReplicasPerNodeGroup=aws.Int64(int64(v.(int)))
}ifnumCacheClusters,ok:=d.GetOk("num_cache_clusters");ok{
input.NumCacheClusters=aws.Int64(int64(numCacheClusters.(int)))
}ifuserGroupIds:=d.Get("user_group_ids").(*schema.Set);userGroupIds.Len()>0{
input.UserGroupIds=flex.ExpandStringSet(userGroupIds)
}output,err:=conn.CreateReplicationGroupWithContext(ctx,input)//Somepartitions(e.g.ISO)maynotsupporttag-on-create.
ifinput.Tags!=nil&&errs.IsUnsupportedOperationInPartitionError(conn.PartitionID,err){
input.Tags=niloutput,err=conn.CreateReplicationGroupWithContext(ctx,input)
}iferr!=nil{
returnsdkdiag.AppendErrorf(diags,"creatingElastiCacheReplicationGroup(%s):%s",replicationGroupID,err)
}d.SetId(aws.StringValue(output.ReplicationGroup.ReplicationGroupId))if_,err:=WaitReplicationGroupAvailable(ctx,conn,d.Id(),d.Timeout(schema.TimeoutCreate));err!=nil{
returnsdkdiag.AppendErrorf(diags,"waitingforElastiCacheReplicationGroup(%s)create:%s",d.Id(),err)
}ifv,ok:=d.GetOk("global_replication_group_id");ok{
//Whenaddingareplicationgrouptoaglobalreplicationgroup,thereplicationgroupcanbeinthe"available"
//state,buttheglobalreplicationgroupcanstillbeinthe"modifying"state.Waitforthereplicationgroup
//tobefullyaddedtotheglobalreplicationgroup.
//APIcallstotheglobalreplicationgroupcanbemadeinanyregion.
if_,err:=waitGlobalReplicationGroupAvailable(ctx,conn,v.(string),globalReplicationGroupDefaultCreatedTimeout);err!=nil{
returnsdkdiag.AppendErrorf(diags,"waitingforElastiCacheGlobalReplicationGroup(%s)tobeavailable:%s",v,err)
}
}//Forpartitionsnotsupportingtag-on-create,attempttagaftercreate.
iftags:=getTagsIn(ctx);input.Tags==nil&&len(tags)>0{
err:=createTags(ctx,conn,aws.StringValue(output.ReplicationGroup.ARN),tags)//Ifdefaulttagsonly,continue.Otherwise,error.
ifv,ok:=d.GetOk(names.AttrTags);(!ok||len(v.(map[string]interface{}))==0)&&errs.IsUnsupportedOperationInPartitionError(conn.PartitionID,err){
returnappend(diags,resourceReplicationGroupRead(ctx,d,meta)...)
}iferr!=nil{
returnsdkdiag.AppendErrorf(diags,"settingElastiCacheReplicationGroup(%s)tags:%s",d.Id(),err)
}
}returnappend(diags,resourceReplicationGroupRead(ctx,d,meta)...)
}
funcresourceReplicationGroupRead(ctxcontext.Context,d*schema.ResourceData,metainterface{})diag.Diagnostics{
vardiagsdiag.Diagnostics
conn:=meta.(*conns.AWSClient).ElastiCacheConn(ctx)rgp,err:=FindReplicationGroupByID(ctx,conn,d.Id())
if!d.IsNewResource()&&tfresource.NotFound(err){
log.Printf("[WARN]ElastiCacheReplicationGroup(%s)notfound,removingfromstate",d.Id())
d.SetId("")
returndiags
}
iferr!=nil{
returnsdkdiag.AppendErrorf(diags,"readingElastiCacheReplicationGroup(%s):%s",d.Id(),err)
}ifaws.StringValue(rgp.Status)==ReplicationGroupStatusDeleting{
log.Printf("[WARN]ElastiCacheReplicationGroup(%s)iscurrentlyinthe`deleting`status,removingfromstate",d.Id())
d.SetId("")
returndiags
}ifrgp.GlobalReplicationGroupInfo!=nil&&rgp.GlobalReplicationGroupInfo.GlobalReplicationGroupId!=nil{
d.Set("global_replication_group_id",rgp.GlobalReplicationGroupInfo.GlobalReplicationGroupId)
}ifrgp.AutomaticFailover!=nil{
switchstrings.ToLower(aws.StringValue(rgp.AutomaticFailover)){
caseelasticache.AutomaticFailoverStatusDisabled,elasticache.AutomaticFailoverStatusDisabling:
d.Set("automatic_failover_enabled",false)
caseelasticache.AutomaticFailoverStatusEnabled,elasticache.AutomaticFailoverStatusEnabling:
d.Set("automatic_failover_enabled",true)
default:
log.Printf("UnknownAutomaticFailoverstate%q",aws.StringValue(rgp.AutomaticFailover))
}
}ifrgp.MultiAZ!=nil{
switchstrings.ToLower(aws.StringValue(rgp.MultiAZ)){
caseelasticache.MultiAZStatusEnabled:
d.Set("multi_az_enabled",true)
caseelasticache.MultiAZStatusDisabled:
d.Set("multi_az_enabled",false)
default:
log.Printf("UnknownMultiAZstate%q",aws.StringValue(rgp.MultiAZ))
}
}d.Set("kms_key_id",rgp.KmsKeyId)
d.Set("description",rgp.Description)
d.Set("num_cache_clusters",len(rgp.MemberClusters))
iferr:=d.Set("member_clusters",flex.FlattenStringSet(rgp.MemberClusters));err!=nil{
returnsdkdiag.AppendErrorf(diags,"settingmember_clusters:%s",err)
}d.Set("num_node_groups",len(rgp.NodeGroups))
d.Set("replicas_per_node_group",len(rgp.NodeGroups[0].NodeGroupMembers)-1)d.Set("cluster_enabled",rgp.ClusterEnabled)
d.Set("replication_group_id",rgp.ReplicationGroupId)
d.Set("arn",rgp.ARN)
d.Set("data_tiering_enabled",aws.StringValue(rgp.DataTiering)==elasticache.DataTieringStatusEnabled)d.Set("log_delivery_configuration",flattenLogDeliveryConfigurations(rgp.LogDeliveryConfigurations))
d.Set("snapshot_window",rgp.SnapshotWindow)
d.Set("snapshot_retention_limit",rgp.SnapshotRetentionLimit)ifrgp.ConfigurationEndpoint!=nil{
d.Set("port",rgp.ConfigurationEndpoint.Port)
d.Set("configuration_endpoint_address",rgp.ConfigurationEndpoint.Address)
}else{
log.Printf("[DEBUG]ElastiCacheReplicationGroup(%s)ConfigurationEndpointisnil",d.Id())ifrgp.NodeGroups[0].PrimaryEndpoint!=nil{
log.Printf("[DEBUG]ElastiCacheReplicationGroup(%s)PrimaryEndpointisnotnil",d.Id())
d.Set("port",rgp.NodeGroups[0].PrimaryEndpoint.Port)
d.Set("primary_endpoint_address",rgp.NodeGroups[0].PrimaryEndpoint.Address)
}ifrgp.NodeGroups[0].ReaderEndpoint!=nil{
d.Set("reader_endpoint_address",rgp.NodeGroups[0].ReaderEndpoint.Address)
}
}d.Set("user_group_ids",rgp.UserGroupIds)//TagscannotbereadwhenthereplicationgroupisnotAvailable
log.Printf("[DEBUG]WaitingforElastiCacheReplicationGroup(%s)tobecomeavailable",d.Id())_,err=WaitReplicationGroupAvailable(ctx,conn,d.Id(),d.Timeout(schema.TimeoutUpdate))
iferr!=nil{
returnsdkdiag.AppendErrorf(diags,"waitingforElastiCacheReplicationGrouptobeavailable(%s):%s",aws.StringValue(rgp.ARN),err)
}log.Printf("[DEBUG]ElastiCacheReplicationGroup(%s):Checkingunderlyingcacheclusters",d.Id())//Thissectionreadssettingsthatrequirecheckingtheunderlyingcacheclusters
ifrgp.NodeGroups!=nil&&rgp.NodeGroups[0]!=nil&&len(rgp.NodeGroups[0].NodeGroupMembers)!=0{
cacheCluster:=rgp.NodeGroups[0].NodeGroupMembers[0]res,err:=conn.DescribeCacheClustersWithContext(ctx,&elasticache.DescribeCacheClustersInput{
CacheClusterId:cacheCluster.CacheClusterId,
ShowCacheNodeInfo:aws.Bool(true),
})
iferr!=nil{
returnsdkdiag.AppendErrorf(diags,"readingElastiCacheReplicationGroup(%s):readingCacheCluster(%s):%s",d.Id(),aws.StringValue(cacheCluster.CacheClusterId),err)
}iflen(res.CacheClusters)==0{
returndiags
}c:=res.CacheClusters[0]iferr:=setFromCacheCluster(d,c);err!=nil{
returnsdkdiag.AppendErrorf(diags,"readingElastiCacheReplicationGroup(%s):readingCacheCluster(%s):%s",d.Id(),aws.StringValue(cacheCluster.CacheClusterId),err)
}d.Set("at_rest_encryption_enabled",c.AtRestEncryptionEnabled)
d.Set("transit_encryption_enabled",c.TransitEncryptionEnabled)ifc.AuthTokenEnabled!=nil&&!aws.BoolValue(c.AuthTokenEnabled){
d.Set("auth_token",nil)
}
}returndiags
}
funcresourceReplicationGroupUpdate(ctxcontext.Context,d*schema.ResourceData,metainterface{})diag.Diagnostics{
vardiagsdiag.Diagnostics
conn:=meta.(*conns.AWSClient).ElastiCacheConn(ctx)ifd.HasChangesExcept("tags","tags_all"){
ifd.HasChanges(
"num_node_groups",
"replicas_per_node_group",
){
err:=modifyReplicationGroupShardConfiguration(ctx,conn,d)
iferr!=nil{
returnsdkdiag.AppendErrorf(diags,"modifyingElastiCacheReplicationGroup(%s)shardconfiguration:%s",d.Id(),err)
}
}elseifd.HasChange("num_cache_clusters"){
err:=modifyReplicationGroupNumCacheClusters(ctx,conn,d,"num_cache_clusters")
iferr!=nil{
returnsdkdiag.AppendErrorf(diags,"modifyingElastiCacheReplicationGroup(%s)clusters:%s",d.Id(),err)
}
}requestUpdate:=false
input:=&elasticache.ModifyReplicationGroupInput{
ApplyImmediately:aws.Bool(d.Get("apply_immediately").(bool)),
ReplicationGroupId:aws.String(d.Id()),
}ifd.HasChange("description"){
input.ReplicationGroupDescription=aws.String(d.Get("description").(string))
requestUpdate=true
}ifd.HasChange("automatic_failover_enabled"){
input.AutomaticFailoverEnabled=aws.Bool(d.Get("automatic_failover_enabled").(bool))
requestUpdate=true
}ifd.HasChange("auto_minor_version_upgrade"){
v:=d.Get("auto_minor_version_upgrade")
ifv,null,_:=nullable.Bool(v.(string)).Value();!null{
input.AutoMinorVersionUpgrade=aws.Bool(v)
}
requestUpdate=true
}ifd.HasChange("security_group_ids"){
ifattr:=d.Get("security_group_ids").(*schema.Set);attr.Len()>0{
input.SecurityGroupIds=flex.ExpandStringSet(attr)
requestUpdate=true
}
}ifd.HasChange("security_group_names"){
ifattr:=d.Get("security_group_names").(*schema.Set);attr.Len()>0{
input.CacheSecurityGroupNames=flex.ExpandStringSet(attr)
requestUpdate=true
}
}ifd.HasChange("log_delivery_configuration"){
oldLogDeliveryConfig,newLogDeliveryConfig:=d.GetChange("log_delivery_configuration")input.LogDeliveryConfigurations=[]*elasticache.LogDeliveryConfigurationRequest{}
logTypesToSubmit:=make(map[string]bool)currentLogDeliveryConfig:=newLogDeliveryConfig.(*schema.Set).List()
for_,current:=rangecurrentLogDeliveryConfig{
logDeliveryConfigurationRequest:=expandLogDeliveryConfigurations(current.(map[string]interface{}))
logTypesToSubmit[*logDeliveryConfigurationRequest.LogType]=true
input.LogDeliveryConfigurations=append(input.LogDeliveryConfigurations,&logDeliveryConfigurationRequest)
}previousLogDeliveryConfig:=oldLogDeliveryConfig.(*schema.Set).List()
for_,previous:=rangepreviousLogDeliveryConfig{
logDeliveryConfigurationRequest:=expandEmptyLogDeliveryConfigurations(previous.(map[string]interface{}))
//ifsomethingwasremoved,sendanemptyrequest
if!logTypesToSubmit[*logDeliveryConfigurationRequest.LogType]{
input.LogDeliveryConfigurations=append(input.LogDeliveryConfigurations,&logDeliveryConfigurationRequest)
}
}
requestUpdate=true
}ifd.HasChange("maintenance_window"){
input.PreferredMaintenanceWindow=aws.String(d.Get("maintenance_window").(string))
requestUpdate=true
}ifd.HasChange("multi_az_enabled"){
input.MultiAZEnabled=aws.Bool(d.Get("multi_az_enabled").(bool))
requestUpdate=true
}ifd.HasChange("notification_topic_arn"){
input.NotificationTopicArn=aws.String(d.Get("notification_topic_arn").(string))
requestUpdate=true
}ifd.HasChange("parameter_group_name"){
input.CacheParameterGroupName=aws.String(d.Get("parameter_group_name").(string))
requestUpdate=true
}ifd.HasChange("engine_version"){
input.EngineVersion=aws.String(d.Get("engine_version").(string))
requestUpdate=true
}ifd.HasChange("snapshot_retention_limit"){
//ThisisarealhacktosettheSnapshottingClusterIDtobethefirstClusterintheRG
o,_:=d.GetChange("snapshot_retention_limit")
ifo.(int)==0{
input.SnapshottingClusterId=aws.String(fmt.Sprintf("%s-001",d.Id()))
}input.SnapshotRetentionLimit=aws.Int64(int64(d.Get("snapshot_retention_limit").(int)))
requestUpdate=true
}ifd.HasChange("snapshot_window"){
input.SnapshotWindow=aws.String(d.Get("snapshot_window").(string))
requestUpdate=true
}ifd.HasChange("node_type"){
input.CacheNodeType=aws.String(d.Get("node_type").(string))
requestUpdate=true
}ifd.HasChange("user_group_ids"){
old,new:=d.GetChange("user_group_ids")
newSet:=new.(*schema.Set)
oldSet:=old.(*schema.Set)
add:=newSet.Difference(oldSet)
remove:=oldSet.Difference(newSet)ifadd.Len()>0{
input.UserGroupIdsToAdd=flex.ExpandStringSet(add)
requestUpdate=true
}ifremove.Len()>0{
input.UserGroupIdsToRemove=flex.ExpandStringSet(remove)
requestUpdate=true
}
}ifrequestUpdate{
_,err:=conn.ModifyReplicationGroupWithContext(ctx,input)
iferr!=nil{
returnsdkdiag.AppendErrorf(diags,"updatingElastiCacheReplicationGroup(%s):%s",d.Id(),err)
}_,err=WaitReplicationGroupAvailable(ctx,conn,d.Id(),d.Timeout(schema.TimeoutUpdate))
iferr!=nil{
returnsdkdiag.AppendErrorf(diags,"waitingforElastiCacheReplicationGroup(%s)toupdate:%s",d.Id(),err)
}
}ifd.HasChange("auth_token"){
params:=&elasticache.ModifyReplicationGroupInput{
ApplyImmediately:aws.Bool(true),
ReplicationGroupId:aws.String(d.Id()),
AuthTokenUpdateStrategy:aws.String("ROTATE"),
AuthToken:aws.String(d.Get("auth_token").(string)),
}_,err:=conn.ModifyReplicationGroupWithContext(ctx,params)
iferr!=nil{
returnsdkdiag.AppendErrorf(diags,"changingauth_tokenforElastiCacheReplicationGroup(%s):%s",d.Id(),err)
}_,err=WaitReplicationGroupAvailable(ctx,conn,d.Id(),d.Timeout(schema.TimeoutUpdate))
iferr!=nil{
returnsdkdiag.AppendErrorf(diags,"waitingforElastiCacheReplicationGroup(%s)auth_tokenchange:%s",d.Id(),err)
}
}
}returnappend(diags,resourceReplicationGroupRead(ctx,d,meta)...)
}
funcresourceReplicationGroupDelete(ctxcontext.Context,d*schema.ResourceData,metainterface{})diag.Diagnostics{
vardiagsdiag.Diagnostics
conn:=meta.(*conns.AWSClient).ElastiCacheConn(ctx)v,hasGlobalReplicationGroupID:=d.GetOk("global_replication_group_id")
ifhasGlobalReplicationGroupID{
globalReplicationGroupID:=v.(string)
err:=DisassociateReplicationGroup(ctx,conn,globalReplicationGroupID,d.Id(),meta.(*conns.AWSClient).Region,GlobalReplicationGroupDisassociationReadyTimeout)
iferr!=nil{
returnsdkdiag.AppendErrorf(diags,"disassociatingElastiCacheReplicationGroup(%s)fromGlobalReplicationGroup(%s):%s",d.Id(),globalReplicationGroupID,err)
}
}varfinalSnapshotID=d.Get("final_snapshot_identifier").(string)
err:=deleteReplicationGroup(ctx,d.Id(),conn,finalSnapshotID,d.Timeout(schema.TimeoutDelete))
iferr!=nil{
returnsdkdiag.AppendErrorf(diags,"deletingElastiCacheReplicationGroup(%s):%s",d.Id(),err)
}ifhasGlobalReplicationGroupID{
paramGroupName:=d.Get("parameter_group_name").(string)
ifparamGroupName!=""{
err:=deleteParameterGroup(ctx,conn,paramGroupName)
iftfawserr.ErrCodeEquals(err,elasticache.ErrCodeCacheParameterGroupNotFoundFault){
returndiags
}
iferr!=nil{
returnsdkdiag.AppendErrorf(diags,"deletingElastiCacheParameterGroup(%s):%s",d.Id(),err)
}
}
}returndiags
}
funcDisassociateReplicationGroup(ctxcontext.Context,conn*elasticache.ElastiCache,globalReplicationGroupID,id,regionstring,readyTimeouttime.Duration)error{
input:=&elasticache.DisassociateGlobalReplicationGroupInput{
GlobalReplicationGroupId:aws.String(globalReplicationGroupID),
ReplicationGroupId:aws.String(id),
ReplicationGroupRegion:aws.String(region),
}
err:=retry.RetryContext(ctx,readyTimeout,
func()*retry.RetryError{
_,err:=conn.DisassociateGlobalReplicationGroupWithContext(ctx,input)
iftfawserr.ErrCodeEquals(err,elasticache.ErrCodeGlobalReplicationGroupNotFoundFault){
returnnil
}
iftfawserr.ErrCodeEquals(err,elasticache.ErrCodeInvalidGlobalReplicationGroupStateFault){
returnretry.RetryableError(err)
}
iferr!=nil{
returnretry.NonRetryableError(err)
}returnnil
})
iftfresource.TimedOut(err){
_,err=conn.DisassociateGlobalReplicationGroupWithContext(ctx,input)
}
iftfawserr.ErrMessageContains(err,elasticache.ErrCodeInvalidParameterValueException,"isnotassociatedwithGlobalReplicationGroup"){
returnnil
}
iftfawserr.ErrCodeEquals(err,elasticache.ErrCodeInvalidGlobalReplicationGroupStateFault){
returnfmt.Errorf("triedfor%s:%w",readyTimeout.String(),err)
}iferr!=nil{
returnerr
}_,err=waitGlobalReplicationGroupMemberDetached(ctx,conn,globalReplicationGroupID,id)
iferr!=nil{
returnfmt.Errorf("waitingforcompletion:%w",err)
}returnnil
}
funcdeleteReplicationGroup(ctxcontext.Context,replicationGroupIDstring,conn*elasticache.ElastiCache,finalSnapshotIDstring,timeouttime.Duration)error{
input:=&elasticache.DeleteReplicationGroupInput{
ReplicationGroupId:aws.String(replicationGroupID),
}
iffinalSnapshotID!=""{
input.FinalSnapshotIdentifier=aws.String(finalSnapshotID)
}//10minutesshouldgiveanycreating/deletingcacheclustersorsnapshotstimetocomplete
err:=retry.RetryContext(ctx,10*time.Minute,
func()*retry.RetryError{
_,err:=conn.DeleteReplicationGroupWithContext(ctx,input)
iftfawserr.ErrCodeEquals(err,elasticache.ErrCodeReplicationGroupNotFoundFault){
returnnil
}
//CacheClusteriscreating/deletingorReplicationGroupissnapshotting
//InvalidReplicationGroupState:Cacheclustertf-acc-test-uqhe-003isnotinavalidstatetobedeleted
iftfawserr.ErrCodeEquals(err,elasticache.ErrCodeInvalidReplicationGroupStateFault){
returnretry.RetryableError(err)
}
iferr!=nil{
returnretry.NonRetryableError(err)
}
returnnil
})
iftfresource.TimedOut(err){
_,err=conn.DeleteReplicationGroupWithContext(ctx,input)
}iftfawserr.ErrCodeEquals(err,elasticache.ErrCodeReplicationGroupNotFoundFault){
returnnil
}
iferr!=nil{
returnerr
}_,err=WaitReplicationGroupDeleted(ctx,conn,replicationGroupID,timeout)returnerr
}
funcmodifyReplicationGroupShardConfiguration(ctxcontext.Context,conn*elasticache.ElastiCache,d*schema.ResourceData)error{
ifd.HasChange("num_node_groups"){
err:=modifyReplicationGroupShardConfigurationNumNodeGroups(ctx,conn,d,"num_node_groups")
iferr!=nil{
returnerr
}
}ifd.HasChange("replicas_per_node_group"){
err:=modifyReplicationGroupShardConfigurationReplicasPerNodeGroup(ctx,conn,d,"replicas_per_node_group")
iferr!=nil{
returnerr
}
}returnnil
}
funcmodifyReplicationGroupShardConfigurationNumNodeGroups(ctxcontext.Context,conn*elasticache.ElastiCache,d*schema.ResourceData,argumentstring)error{
o,n:=d.GetChange(argument)
oldNumNodeGroups:=o.(int)
newNumNodeGroups:=n.(int)input:=&elasticache.ModifyReplicationGroupShardConfigurationInput{
ApplyImmediately:aws.Bool(true),
NodeGroupCount:aws.Int64(int64(newNumNodeGroups)),
ReplicationGroupId:aws.String(d.Id()),
}ifoldNumNodeGroups>newNumNodeGroups{
//NodeGroupIDsare1indexed:0001through0015
//LoopfromhighestoldIDuntilwereachhighestnewID
nodeGroupsToRemove:=[]string{}
fori:=oldNumNodeGroups;i>newNumNodeGroups;i--{
nodeGroupID:=fmt.Sprintf("%04d",i)
nodeGroupsToRemove=append(nodeGroupsToRemove,nodeGroupID)
}
input.NodeGroupsToRemove=aws.StringSlice(nodeGroupsToRemove)
}log.Printf("[DEBUG]ModifyingElastiCacheReplicationGroup(%s)shardconfiguration:%s",d.Id(),input)
_,err:=conn.ModifyReplicationGroupShardConfigurationWithContext(ctx,input)
iferr!=nil{
returnfmt.Errorf("modifyingElastiCacheReplicationGroupshardconfiguration:%w",err)
}_,err=WaitReplicationGroupAvailable(ctx,conn,d.Id(),d.Timeout(schema.TimeoutUpdate))
iferr!=nil{
returnfmt.Errorf("waitingforElastiCacheReplicationGroup(%s)shardreconfigurationcompletion:%w",d.Id(),err)
}returnnil
}
funcmodifyReplicationGroupShardConfigurationReplicasPerNodeGroup(ctxcontext.Context,conn*elasticache.ElastiCache,d*schema.ResourceData,argumentstring)error{
o,n:=d.GetChange(argument)
oldReplicas:=o.(int)
newReplicas:=n.(int)ifnewReplicas>oldReplicas{
input:=&elasticache.IncreaseReplicaCountInput{
ApplyImmediately:aws.Bool(true),
NewReplicaCount:aws.Int64(int64(newReplicas)),
ReplicationGroupId:aws.String(d.Id()),
}
_,err:=conn.IncreaseReplicaCountWithContext(ctx,input)
iferr!=nil{
returnfmt.Errorf("addingElastiCacheReplicationGroup(%s)replicas:%w",d.Id(),err)
}
_,err=WaitReplicationGroupAvailable(ctx,conn,d.Id(),d.Timeout(schema.TimeoutUpdate))
iferr!=nil{
returnfmt.Errorf("waitingforElastiCacheReplicationGroup(%s)replicaaddition:%w",d.Id(),err)
}
}else{
input:=&elasticache.DecreaseReplicaCountInput{
ApplyImmediately:aws.Bool(true),
NewReplicaCount:aws.Int64(int64(newReplicas)),
ReplicationGroupId:aws.String(d.Id()),
}
_,err:=conn.DecreaseReplicaCountWithContext(ctx,input)
iferr!=nil{
returnfmt.Errorf("removingElastiCacheReplicationGroup(%s)replicas:%w",d.Id(),err)
}
_,err=WaitReplicationGroupAvailable(ctx,conn,d.Id(),d.Timeout(schema.TimeoutUpdate))
iferr!=nil{
returnfmt.Errorf("waitingforElastiCacheReplicationGroup(%s)replicaremoval:%w",d.Id(),err)
}
}returnnil
}
funcmodifyReplicationGroupNumCacheClusters(ctxcontext.Context,conn*elasticache.ElastiCache,d*schema.ResourceData,argumentstring)error{
o,n:=d.GetChange(argument)
oldNumberCacheClusters:=o.(int)
newNumberCacheClusters:=n.(int)varerrerror
ifnewNumberCacheClusters>oldNumberCacheClusters{
err=increaseReplicationGroupNumCacheClusters(ctx,conn,d.Id(),newNumberCacheClusters,d.Timeout(schema.TimeoutUpdate))
}elseifnewNumberCacheClusters<oldNumberCacheClusters{
err=decreaseReplicationGroupNumCacheClusters(ctx,conn,d.Id(),newNumberCacheClusters,d.Timeout(schema.TimeoutUpdate))
}
returnerr
}
funcincreaseReplicationGroupNumCacheClusters(ctxcontext.Context,conn*elasticache.ElastiCache,replicationGroupIDstring,newNumberCacheClustersint,timeouttime.Duration)error{
input:=&elasticache.IncreaseReplicaCountInput{
ApplyImmediately:aws.Bool(true),
NewReplicaCount:aws.Int64(int64(newNumberCacheClusters-1)),
ReplicationGroupId:aws.String(replicationGroupID),
}
_,err:=conn.IncreaseReplicaCountWithContext(ctx,input)
iferr!=nil{
returnfmt.Errorf("addingElastiCacheReplicationGroup(%s)replicas:%w",replicationGroupID,err)
}_,err=WaitReplicationGroupMemberClustersAvailable(ctx,conn,replicationGroupID,timeout)
iferr!=nil{
returnfmt.Errorf("waitingforElastiCacheReplicationGroup(%s)replicaaddition:%w",replicationGroupID,err)
}returnnil
}
funcdecreaseReplicationGroupNumCacheClusters(ctxcontext.Context,conn*elasticache.ElastiCache,replicationGroupIDstring,newNumberCacheClustersint,timeouttime.Duration)error{
input:=&elasticache.DecreaseReplicaCountInput{
ApplyImmediately:aws.Bool(true),
NewReplicaCount:aws.Int64(int64(newNumberCacheClusters-1)),
ReplicationGroupId:aws.String(replicationGroupID),
}
_,err:=conn.DecreaseReplicaCountWithContext(ctx,input)
iferr!=nil{
returnfmt.Errorf("removingElastiCacheReplicationGroup(%s)replicas:%w",replicationGroupID,err)
}_,err=WaitReplicationGroupMemberClustersAvailable(ctx,conn,replicationGroupID,timeout)
iferr!=nil{
returnfmt.Errorf("waitingforElastiCacheReplicationGroup(%s)replicaremoval:%w",replicationGroupID,err)
}returnnil
}varvalidateReplicationGroupIDschema.SchemaValidateFunc=validation.All(
validation.StringLenBetween(1,40),
validation.StringMatch(regexache.MustCompile(`^[0-9A-Za-z-]+$`),"mustcontainonlyalphanumericcharactersandhyphens"),
validation.StringMatch(regexache.MustCompile(`^[A-Za-z]`),"mustbeginwithaletter"),
validation.StringDoesNotMatch(regexache.MustCompile(`--`),"cannotcontaintwoconsecutivehyphens"),
validation.StringDoesNotMatch(regexache.MustCompile(`-$`),"cannotendwithahyphen"),
)
