// Code generated by internal/generate/servicepackages/main.go; DO NOT EDIT.

package datapipeline

import (
"context"

aws_sdkv1 "github.com/aws/aws-sdk-go/aws"
session_sdkv1 "github.com/aws/aws-sdk-go/aws/session"
datapipeline_sdkv1 "github.com/aws/aws-sdk-go/service/datapipeline"
"github.com/hashicorp/terraform-provider-aws/internal/conns"
"github.com/hashicorp/terraform-provider-aws/internal/types"
"github.com/hashicorp/terraform-provider-aws/names"
)

type servicePackage struct{}

funcrn []*types.ServicePackageFrameworkDataSource{}
}

func (p *servicePackage) FrameworkResources(ctx context.Context) []*types.ServicePackageFrameworkResource {
func

func (p *servicePackage) SDKDataSources(ctx context.Context) []*types.ServicePackageSDKDataSource {
return []*types.ServicePackageSDKDataSource{
funcory:  DataSourcePipeline,
TypeName: "aws_datapipeline_pipeline",
},
{
Factory:  DataSourcePipelineDefinition,
TypeName: "aws_datapipeline_pipeline_definition",
},
}
}

func (p *servicePackage) SDKResources(ctx context.Context) []*types.ServicePackageSDKResource {
return []*types.ServicePackageSDKResource{
{
funcName: "aws_datapipeline_pipeline",
Name:     "Pipeline",
Tags: &types.ServicePackageResourceTags{
IdentifierAttribute: "id",
},
},
{
Factory:  ResourcePipelineDefinition,
TypeName: "aws_datapipeline_pipeline_definition",
},
}
}

func (p *servicePackage) ServicePackageName() string {
return names.DataPipeline
}

func (p *servicePackage) NewConn(ctx context.Context, config map[string]any) (*datapipeline_sdkv1.DataPipeline, error) {
sess := config["session"].(*session_sdkv1.Session)

return datapipeline_sdkv1.New(sess.Copy(&aws_sdkv1.Config{Endpoint: aws_sdkv1.String(config["endpoint"].(string))})), nil
}
func ServicePackage(ctx context.Context) conns.ServicePackage {
return &servicePackage{}
}
func